packages:
  - "."

strictDepBuilds: true
dangerouslyAllowAllBuilds: false
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@emdash-cms/admin@0.39.1'
  - '@emdash-cms/auth@0.39.1'
  - '@emdash-cms/blocks@0.39.1'
  - '@emdash-cms/cloudflare@0.39.1'
  - '@emdash-cms/gutenberg-to-portable-text@0.39.1'
  - '@emdash-cms/plugin-test@0.2.1'
  - emdash@0.39.1
